### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gree303** [python3xdev/Automated-YouTube-Channel-Bot#1]
Hi, I'm getting an error and have no clue what's wrong. Can you tell what's happening? Thanks
Error:
 File "igbot.py", line 51
    print(f"Scraping -> Username: {acc.username} | Followers: {acc.followers} | Posts: {acc.mediacount}")
                                                                                                       ^
SyntaxError: invalid syntax

I've changed the following files:
- client_secret.json (Google API client_id + secret)
- main.py - line 17: IG user + pw

**Comment by python3xdev** [comment]
Hello @gree303, nothing should be broken. Maybe the indentation is mixed? I use tabs while writing code. If your IDE/Text Editor has a convert to spaces or tabs option, use that. If it does not, you could try this website https://codebeautify.org/python-formatter-beautifier , Or others similar to it. Hope this fixes the problem.

Edit: Also make sure you are using python 3 and not python 2

**Comment by python3xdev** [comment]
Due to no reply for 12 days, this issue will be closed.
